export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAIL = 'UPDATE_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_FAIL';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_FAIL = 'GET_ROOM_FAIL';
export const GET_ROOMS_FAIL = 'GET_ROOM_FAIL';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';
export const ADD_ROOM_MEMBER_SUCCESS = 'ADD_ROOM_MEMBER_SUCCESS'
export const ADD_ROOM_MEMBER_FAIL = 'ADD_ROOM_MEMBER_FAIL'
export const GET_ALL_ROOM_MEMBERS_SUCCESS = 'GET_ALL_ROOM_MEMBERS_SUCCESS';
export const GET_ALL_ROOM_MEMBERS_FAIL = 'GET_ALL_ROOM_MEMBERS_FAIL';
export const LEFT_ROOM_SUCCESS = 'LEFT_ROOM_SUCCESS';
export const LEFT_ROOM_FAIL = 'LEFT_ROOM_FAIL';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';


export const GET_ALL_EXPENSE_ROOM_SUCCESS = 'GET_ALL_EXPENSE_ROOM_SUCCESS';
export const GET_ALL_EXPENSE_ROOM_FAIL = 'GET_ALL_EXPENSE_ROOM_FAIL';
export const GET_ALL_EXPENSES_SUCCESS = 'GET_ALL_EXPENSES_SUCCESS';
export const GET_ALL_EXPENSES_FAIL = 'GET_ALL_EXPENSES_FAIL';
export const POST_ADD_EXPENSES_SUCCESS = 'POST_ADD_EXPENSES_SUCCESS';
export const POST_ADD_EXPENSES_FAIL = 'POST_ADD_EXPENSES_FAIL';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_FAILED = 'DELETE_EXPENSE_FAIL';

export const GET_ALL_TRANSACTION_SUCCESS = 'GET_ALL_TRANSACTION_SUCCESS';
export const GET_ALL_TRANSACTION_FAIL = 'GET_ALL_TRANSACTION_FAIL';
 
export const GET_NET_TOTAL_SUCCESS = 'GET_NET_TOTAL_SUCCESS';
export const GET_NET_TOTAL_FAIL = 'GET_NET_TOTAL_FAIL';

export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';




 
 
    